spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passion-hub?autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: password
  liquibase:
    contexts: dev
    change-log: classpath:/db/changelog/master.xml
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  h2:
    console:
      enabled: true
app:
  storage:
    location: ./uploads/